language: scala
sudo: true

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - oraclejdk7
  - oraclejdk8

matrix:
  include:
  - scala: 2.12.1
    jdk: oraclejdk8

os:
  - linux

before_script:
  - sh src/test/resources/setup_travis.sh

